Fixed shellcheck warnings.

diff --git a/bin/build-kernel-initrd b/bin/build-kernel-initrd
--- a/bin/build-kernel-initrd
+++ b/bin/build-kernel-initrd
@@ -1,13 +1,28 @@
 #! /bin/bash -f
+# shellcheck disable=SC2164
+
+function die
+{
+    local msg ev
+    msg="ERROR: ${1}"
+    ev="${2}"
+    
+    if [[ -z "${ev}" ]] || (( ev < 1 )); then
+        ev=1
+    fi
+    
+    echo "${msg}" >&2
+    exit "${ev}"
+}
 
 function okorfail
 {
 	local result=$?
-	if (( ! ${result} )); then
+	if (( ! result )); then
 		echo "ok." 
 	else
 		echo "failed [${result}]."
-		EXITSTATUS=${result}
+		EXITSTATUS="${result}"
 	fi
 
 	return ${result}
@@ -16,14 +31,16 @@ function okorfail
 EXITSTATUS=0
 
 # Check that the current kernel sources have at least been configured.
-if [[ ! -f /usr/src/linux/.config ]]
-then
-	echo "You need to configure your kernel sources first!"
-	exit
-fi
+[[ -f /usr/src/linux/.config ]] || die "You need to configure your kernel sources first!" 1
 
 # Try to source make.conf
-[[ -f "/etc/make.conf" ]] && source /etc/make.conf || source /etc/portage/make.conf
+if [[ -f "/etc/make.conf" ]]; then
+    # shellcheck disable=SC1091
+    source /etc/make.conf || die "Unable to read /etc/make.conf" 2
+else
+    # shellcheck disable=SC1091
+    source /etc/portage/make.conf || die "Unable to read /etc/portage/make.conf" 2
+fi
 
 # Get the current kernel version.  Build it and its modules.
 pushd /usr/src >/dev/null
@@ -33,12 +50,16 @@ KVER=$(make kernelversion)
 echo "Building kernel and initrd images for kernel version ${KVER}"
 
 echo -n "    Building kernel..."
+# We want ${MAKEOPTS} to split
+# shellcheck disable=SC2086
 make ${MAKEOPTS} >/dev/null 2>&1 
-okorfail || exit ${EXITSTATUS}
+okorfail || exit "${EXITSTATUS}"
 
 echo -n "    Building modules..."
+# We want ${MAKEOPTS} to split
+# shellcheck disable=SC2086
 make ${MAKEOPTS} modules_install >/dev/null 2>&1
-okorfail || exit ${EXITSTATUS}
+okorfail || exit "${EXITSTATUS}"
 
 popd >/dev/null
 
@@ -46,12 +67,12 @@ popd >/dev/null
 # is current and therefore which revision is next.
 mkdir -p configs
 pushd configs >/dev/null
-CVER=$(find -iname config-${KVER}* | sort --version-sort | tail --lines=1)
+CVER=$(find . -iname "config-${KVER}*" | sort --version-sort | tail --lines=1)
 CVER="${CVER##*/}"
 if [[ -n "${CVER}" ]]
 then
 	echo "    Latest configurarion revision is ${CVER}"
-	CVER=$(echo ${CVER} | awk 'BEGIN { FS="-c" } { printf "%s-c%02d", $1, $2+1 }')
+	CVER=$(echo "${CVER}" | awk 'BEGIN { FS="-c" } { printf "%s-c%02d", $1, $2+1 }')
 else
 	echo "    Latest configuration unavailable"
 	CVER="config-${KVER}-c01"
@@ -70,32 +91,32 @@ echo -n "    Copying kernel image..."
 mkdir -p images/kernel
 ARCH=$(uname -m)
 [[ "${ARCH}" != 'x86_64' ]] && ARCH="x86"
-cp linux/arch/${ARCH}/boot/bzImage images/kernel/linux-${CVER}
-okorfail || exit ${EXITSTATUS}
+cp "linux/arch/${ARCH}/boot/bzImage" "images/kernel/linux-${CVER}"
+okorfail || exit "${EXITSTATUS}"
 
 # Build a disk-boot capable initrd.
 echo -n "    Building disk-boot kernel initrd..."
 mkdir -p images/diskboot
-dracut images/diskboot/linux-${CVER}.img ${KVER} \
+dracut "images/diskboot/linux-${CVER}.img" "${KVER}" \
 	--mdadmconf --nolvmconf --no-hostonly --omit "network nbd nfs rbd iscsi" --omit-drivers "e1000e"  >/dev/null 2>&1
-okorfail || exit ${EXITSTATUS}
-chmod +r images/diskboot/linux-${CVER}.img
+okorfail || exit "${EXITSTATUS}"
+chmod +r "images/diskboot/linux-${CVER}.img"
 
 # Build a net-boot capable initrd.
 echo -n "    Building net-boot kernel initrd..."
 mkdir -p images/netboot
-dracut images/netboot/linux-${CVER}.img ${KVER} \
+dracut "images/netboot/linux-${CVER}.img" "${KVER}" \
 	--nomdadmconf --nolvmconf --no-hostonly --omit "mdraid lvm lkg rbd" >/dev/null 2>&1
-okorfail || exit ${EXITSTATUS}
-chmod +r images/netboot/linux-${CVER}.img
+okorfail || exit "${EXITSTATUS}"
+chmod +r "images/netboot/linux-${CVER}.img"
 
 # Build an rbd-boot capable initrd.
 echo -n "    Building rbd-boot kernel initrd..."
 mkdir -p images/rbdboot
-dracut images/rbdboot/linux-${CVER}.img ${KVER} \
+dracut "images/rbdboot/linux-${CVER}.img" "${KVER}" \
     --nomdadmconf --nolvmconf --no-hostonly --omit "mdraid lvm lkg nfs" >/dev/null 2>&1
-okorfail || exit ${EXITSTATUS}
-chmod +r images/rbdboot/linux-${CVER}.img
+okorfail || exit "${EXITSTATUS}"
+chmod +r "images/rbdboot/linux-${CVER}.img"
 
 
 
diff --git a/bin/free-distfiles-space b/bin/free-distfiles-space
--- a/bin/free-distfiles-space
+++ b/bin/free-distfiles-space
@@ -1,26 +1,19 @@
 #! /bin/bash
+# shellcheck disable=SC2164
 
 function versioninfo
 {
-	VERSION="$Revision$"
-	VERSION="${VERSION%\ \$}"; VERSION="${VERSION#\:}"; VERSION="${VERSION##\ }"
-	VERSION="(CVS revision $VERSION)"
-
-	NAME="$Name$"
-	NAME="${NAME%\ \$}"; NAME="${NAME#\:}"; NAME="${NAME##\ }"; NAME="${NAME##release-}"; NAME="${NAME//-/.}"
-
-	echo -ne "$(basename ${0}) ${NAME} ${VERSION}\n"
-
-	echo -e "\nCopyright (C) 2010-2016 MAD Hacking"
-	echo "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
-	echo "This is free software: you are free to change and redistribute it."
-	echo "There is NO WARRANTY, to the extent permitted by law."
+    echo "$(basename "${0}") - version 1.0.0"
+    echo -e "\nCopyright (C) 2010-2019 Hacking Networked Solutions"
+    echo "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
+    echo "This is free software: you are free to change and redistribute it."
+    echo "There is NO WARRANTY, to the extent permitted by law."
 }
 
 function helpscreen
 {
-	NAME=$(basename ${0})
-	echo "Usage: ${NAME} [OPTION]..."
+	CMDNAME=$(basename "${0}")
+	echo "Usage: ${CMDNAME} [OPTION]..."
 	echo "Manages the free space in the DISTDIR"
 	echo
 	echo "  -d, --free-delete              repeatedly delete the oldest files from DISTDIR"
@@ -38,22 +31,30 @@ function helpscreen
     echo "      --version                  output version information and exit"
 }
 
-function error_exit
+function die
 {
-	echo $@
-	exit 1
+    local msg ev
+    msg="ERROR: ${1}"
+    ev="${2}"
+    
+    if [[ -z "${ev}" ]] || (( ev < 1 )); then
+        ev=1
+    fi
+    
+    echo "${msg}" >&2
+    exit "${ev}"
 }
 
 function get_disk_size
 {
-	df -P -B 1 ${1} 2>/dev/null | tail -1 | awk '{print $2}'
+	df -P -B 1 "${1}" 2>/dev/null | tail -1 | awk '{print $2}'
 
 	return $?
 }
 
 function get_free_space
 {
-	df -P -B 1 ${1} 2>/dev/null | tail -1 | awk '{print $4}'
+	df -P -B 1 "${1}" 2>/dev/null | tail -1 | awk '{print $4}'
 
 	return $?
 }
@@ -78,9 +79,9 @@ do
 			DISPLAYREQUIRED=1
 		;;
 		-s|--source)
-			[[ -z ${2} ]] && error_exit "Error: A source file name was expected!"
-			[[ ! -f ${2} ]] && error_exit "Error: source file \"${2}\" does not exist!"
-			[[ ! -r ${2} ]] && error_exit "Error: source file \"${2}\" is not readable!"
+			[[ -z "${2}" ]] && die "A source file name was expected!"
+			[[ ! -f "${2}" ]] && die "source file \"${2}\" does not exist!"
+			[[ ! -r "${2}" ]] && die "source file \"${2}\" is not readable!"
 			emerge_source="${2}"
 			shift 1
 		;;
@@ -101,16 +102,15 @@ done
 
 # Get the location of the DISTDIR
 DISTDIR=$(portageq distdir)
-[[ -z ${DISTDIR} || (( ! $? )) ]] &&  echo "ERROR: Unable to locate DISTDIR" >&2 && exit 2
+[[ -z "${DISTDIR}" || (( ! $? )) ]] &&  die "Unable to locate DISTDIR" 2
 
 # If we have been asked to display current free space then...
 if [[ -n ${DISPLAYFREE} ]]; then
-	FREEBYTES=$(get_free_space ${DISTDIR})
-	(( $? )) && echo "Unable to calculate free disk space in DISTDIR (${DISTDIR})" >&2 && exit 1
+	FREEBYTES=$(get_free_space "${DISTDIR}") || die "Unable to calculate free disk space in DISTDIR (${DISTDIR})" 3
 	
-	FREESPACE=$(( ${FREEBYTES} / 1024 )) UNITS="KB"
-	(( ${FREESPACE} > 1024 )) && FREESPACE=$(( ${FREESPACE} / 1024 )) UNITS="MB"
-	(( ${FREESPACE} > 1024 )) && FREESPACE=$(( ${FREESPACE} / 1024 )) UNITS="GB"
+	FREESPACE=$(( FREEBYTES / 1024 )) UNITS="KB"
+	(( FREESPACE > 1024 )) && FREESPACE=$(( FREESPACE / 1024 )) UNITS="MB"
+	(( FREESPACE > 1024 )) && FREESPACE=$(( FREESPACE / 1024 )) UNITS="GB"
 	echo "Free space available in DISTDIR (${DISTDIR}) : ${FREESPACE} ${UNITS} (${FREEBYTES} bytes)"
 fi
 
@@ -120,63 +120,64 @@ if [[ -n ${GETREQUIRED} || -n ${DISPLAYREQUIRED} ]]; then
 	# Eg: SIZESTR="Total: 3 packages (3 upgrades), Size of downloads: 1,497 kB"
 	SIZESTR=""
 	if [[ -n "${emerge_source}" ]]; then
-		SIZESTR=$(cat ${emerge_source} | grep "Size of downloads:")
-		[[ -z "${SIZESTR}" ]] && error_exit "Error: Unable to locate \"Size of downloads:\" in \"${emerge_source}\""
+		SIZESTR=$(grep "Size of downloads:" < "${emerge_source}")
+		[[ -z "${SIZESTR}" ]] && die "Unable to locate \"Size of downloads:\" in \"${emerge_source}\""
 	else
 		SIZESTR=$(emerge -pv${MERGETYPE} world | grep "Size of downloads:")
-		[[ -z "${SIZESTR}" ]] && error_exit "Error: Unable to locate \"Size of downloads:\" in emerge output!"
+		[[ -z "${SIZESTR}" ]] && die "Unable to locate \"Size of downloads:\" in emerge output!"
 	fi
 
 	# SPLIT result string
 	oIFS=$IFS
-	IFS=':' SPLIT1=(${SIZESTR})
-	IFS=' ' SPLIT2=(${SPLIT1[2]})
+	IFS=':' SPLIT1=("${SIZESTR}")
+	IFS=' ' SPLIT2=("${SPLIT1[2]}")
 	IFS=$oIFS
 
 	# Get size and units
 	NUM=${SPLIT2[0]//,/}
-	[[ "${NUM}" == ?(+|-)+([0-9]) ]] && REQSIZE=$(( ${NUM} )) || REQSIZE=0
+	[[ "${NUM}" == ?(+|-)+([0-9]) ]] && REQSIZE=$(( NUM )) || REQSIZE=0
 	UNITS=${SPLIT2[1]}
 
 	# Add 10%
-	REQSIZE=$(( ${REQSIZE} + ${REQSIZE} / 10 ))
+	REQSIZE=$(( REQSIZE + REQSIZE / 10 ))
 
 	# Calculate in bytes
 	shopt -s nocasematch
 	case "$UNITS" in
-		"kb"|"kib") REQBYTES=$(( ${REQSIZE} * 1024 )) ;;
-		"mb"|"mib") REQBYTES=$(( ${REQSIZE} * 1024 * 1024 )) ;;
-		"gb"|"gib") REQBYTES=$(( ${REQSIZE} * 1024 * 1024 * 1024 )) ;;
+		"kb"|"kib") REQBYTES=$(( REQSIZE * 1024 )) ;;
+		"mb"|"mib") REQBYTES=$(( REQSIZE * 1024 * 1024 )) ;;
+		"gb"|"gib") REQBYTES=$(( REQSIZE * 1024 * 1024 * 1024 )) ;;
 	esac
 	shopt -u nocasematch
 
 	# Get the size of the disk, calculate 10% and add to REQBYTES
-	DISKSIZE=$(get_disk_size ${DISTDIR})
-	DISKSIZE=$(( ${DISKSIZE} / 10 ))
-	REQBYTES=$(( ${REQBYTES} + ${DISKSIZE} ))
+	DISKSIZE=$(get_disk_size "${DISTDIR}")
+	DISKSIZE=$(( DISKSIZE / 10 ))
+	REQBYTES=$(( REQBYTES + DISKSIZE ))
 
 	# Recalculate in proper units
-	REQSPACE=$(( ${REQBYTES} / 1024 )) UNITS="KB"
-	(( ${REQSPACE} > 1024 )) && REQSPACE=$(( ${REQSPACE} / 1024 )) UNITS="MB"
-	(( ${REQSPACE} > 1024 )) && REQSPACE=$(( ${REQSPACE} / 1024 )) UNITS="GB"
+	REQSPACE=$(( REQBYTES / 1024 )) UNITS="KB"
+	(( REQSPACE > 1024 )) && REQSPACE=$(( REQSPACE / 1024 )) UNITS="MB"
+	(( REQSPACE > 1024 )) && REQSPACE=$(( REQSPACE / 1024 )) UNITS="GB"
 
 	# Display result
 	[[ -n ${DISPLAYREQUIRED} ]] && echo "Free space required in DISTDIR (${DISTDIR}) : ${REQSPACE} ${UNITS} (${REQBYTES} bytes)"
 fi
 
 # If we have been asked to free the required space then...
-if [[ -n ${FREEDELETE} ]]; then
+if [[ -n "${FREEDELETE}" ]]; then
 	# Store current directory, repeatedly delete oldest 10 files from distfiles
 	# directory until there is sufficient free space, restore current directory.
-	pushd ${DISTDIR} > /dev/null 
+	pushd "${DISTDIR}" > /dev/null 
 
 	# We may be done already, if so quit	
-	(( $(get_free_space ${DISTDIR}) >= ${REQBYTES} )) && exit
+	(( $(get_free_space "${DISTDIR}") >= REQBYTES )) && exit
 	
 	echo -n "Freeing space for distfiles..."
-	while (( $(get_free_space ${DISTDIR}) < ${REQBYTES} ))
+	while (( $(get_free_space "${DISTDIR}") < REQBYTES ))
 	do 
-	  	rm $(ls -1 --time=atime --sort=time --reverse | head --lines=20) 2>&1 > /dev/null 
+	    # shellcheck disable=SC2012
+	  	rm -f "$(ls -1 --time=atime --sort=time --reverse | head --lines=20)" > /dev/null 2>&1
 	  	echo -n "."
 	done 
 	popd > /dev/null
diff --git a/bin/merge-new-configs b/bin/merge-new-configs
--- a/bin/merge-new-configs
+++ b/bin/merge-new-configs
@@ -2,18 +2,8 @@
 
 function versioninfo
 {
-	VERSION="$Revision$"
-	VERSION="${VERSION%\ \$}"; VERSION="${VERSION#\:}"; VERSION="${VERSION##\ }"
-	VERSION="(CVS revision $VERSION)"
-	
-	NAME="$Name$"
-	NAME="${NAME%\ \$}"; NAME="${NAME#\:}"; NAME="${NAME##\ }"; NAME="${NAME##release-}"; NAME="${NAME//-/.}"
-	[[ -n $NAME ]] && NAME="Version $NAME "
-
-	echo ${CMDNAME}
-	echo ${NAME}${VERSION}
-
-	echo -e "\nCopyright (C) 2010 Hacking Networked Solutions"
+    echo "$(basename "${0}") - version 1.0.0"
+	echo -e "\nCopyright (C) 2010-2020 Hacking Networked Solutions"
 	echo "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
 	echo "This is free software: you are free to change and redistribute it."
 	echo "There is NO WARRANTY, to the extent permitted by law."
@@ -21,6 +11,7 @@ function versioninfo
 
 function helpscreen
 {
+    CMDNAME=$(basename "${0}")
 	echo "Usage: ${CMDNAME} [OPTION]..."
 	echo "Automatically deletes updated configuration files for those files listed"
 	echo "then unconditionally merges remaining configuration files"
@@ -31,9 +22,22 @@ function helpscreen
     echo "      --version                  output version information and exit"
 }
 
+function die
+{
+    local msg ev
+    msg="ERROR: ${1}"
+    ev="${2}"
+    
+    if [[ -z "${ev}" ]] || (( ev < 1 )); then
+        ev=1
+    fi
+    
+    echo "${msg}" >&2
+    exit "${ev}"
+}
+
 # Init local vars
 CFGFILE=/etc/buildspace
-CMDNAME=$(basename ${0})
 
 # Process command line switches
 while [[ $# -gt 0 ]]
@@ -57,23 +61,23 @@ do
 done
 
 # If the config file exists and we can read it do so
-[[ ! -r ${CFGFILE} && -z ${CONFFILES} ]] && echo "Error: No config file (or no read permissions) at ${CFGFILE}" >&2 && exit 2
-source ${CFGFILE}
+# shellcheck disable=SC1090
+source ${CFGFILE} || die "Error: No config file (or no read permissions) at ${CFGFILE}" 2
 
 # Check config
-[[ -z ${CONFFILES} ]] && echo "Error: You have no CONFFILES set in ${CFGFILE} and none were specified" >&2 && exit 2	
+[[ -z ${CONFFILES} ]] && die "Error: You have no CONFFILES set in ${CFGFILE} and none were specified" 3	
 
 # Loop through the files above searching for any configuration files which
 # match.  If any are found for that file display them and delete them.
 echo "Searching for new configurations for:"
 for F in ${CONFFILES}; do
 	echo -n "    ${F} : "
-	FTD=$(find /etc -name "._cfg*${F}*" | xargs -r)
+	FTD=$(find /etc -name "._cfg*${F}*" -print0 | xargs -r -0)
 	if [[ -z ${FTD} ]]; then
 		echo "none."
 	else
-		echo ${FTD}
-		rm -f ${FTD}
+		echo "${FTD}"
+		rm -f "${FTD}"
 	fi
 done
 echo
diff --git a/bin/rebuild-portage-caches b/bin/rebuild-portage-caches
--- a/bin/rebuild-portage-caches
+++ b/bin/rebuild-portage-caches
@@ -2,18 +2,8 @@
 
 function versioninfo
 {
-	VERSION="$Revision$"
-	VERSION="${VERSION%\ \$}"; VERSION="${VERSION#\:}"; VERSION="${VERSION##\ }"
-	VERSION="(CVS revision $VERSION)"
-	
-	NAME="$Name$"
-	NAME="${NAME%\ \$}"; NAME="${NAME#\:}"; NAME="${NAME##\ }"; NAME="${NAME##release-}"; NAME="${NAME//-/.}"
-	[[ -n $NAME ]] && NAME="Version $NAME "
-
-	echo ${CMDNAME}
-	echo ${NAME}${VERSION}
-
-	echo -e "\nCopyright (C) 2010 Hacking Networked Solutions"
+    echo "$(basename "${0}") - version 1.0.0"
+    echo -e "\nCopyright (C) 2010-2020 Hacking Networked Solutions"
 	echo "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
 	echo "This is free software: you are free to change and redistribute it."
 	echo "There is NO WARRANTY, to the extent permitted by law."
@@ -21,6 +11,7 @@ function versioninfo
 
 function helpscreen
 {
+    CMDNAME=$(basename "${0}")
 	echo "Usage: ${CMDNAME}"
 	echo "Rebuilds the portage metadata and, if eix is installed, rebuilds the eix cache"
 	echo
@@ -31,11 +22,12 @@ function helpscreen
 
 function echoq
 {
-	[[ -z ${QUIET} ]] && echo $1 $2 $3 $4
+	[[ -z ${QUIET} ]] && echo "${@}"
 }
 
 function okorfail
 {
+    # shellcheck disable=SC2181
 	if (( ! $? )); then
 		echoq "ok." 
 	else
@@ -46,7 +38,6 @@ function okorfail
 
 # Init global vars
 CFGFILE=/etc/buildspace
-CMDNAME=$(basename ${0})
 EXITSTATUS=0
 
 # Process command line switches
@@ -71,10 +62,11 @@ do
 done
 
 # If the config file exists and we can read it do so
-[[ -r ${CFGFILE} ]] && source ${CFGFILE}
+# shellcheck disable=SC1090
+[[ -r "${CFGFILE}" ]] && source "${CFGFILE}"
 
 # Check to make sure we are being run from inside the buildspace.
-[[ -z "${BUILDSPACE_NAME}" ]] && echo "ERROR: ${CMDNAME} should only be run inside a configured buildspace!" >&2 && exit 1
+[[ -z "${BUILDSPACE_NAME}" ]] && echo "ERROR: $(basename "${0}") should only be run inside a configured buildspace!" >&2 && exit 1
 
 echoq -n "Rebuilding metadata cache for [${BUILDSPACE_NAME}] build-space..." 
 emerge --metadata --quiet 1>/dev/null
diff --git a/bin/remerge-missing-binaries b/bin/remerge-missing-binaries
--- a/bin/remerge-missing-binaries
+++ b/bin/remerge-missing-binaries
@@ -2,26 +2,17 @@
 
 function versioninfo
 {
-	VERSION="$Revision$"
-	VERSION="${VERSION%\ \$}"; VERSION="${VERSION#\:}"; VERSION="${VERSION##\ }"
-	VERSION="(CVS revision $VERSION)"
-	
-	NAME="$Name$"
-	NAME="${NAME%\ \$}"; NAME="${NAME#\:}"; NAME="${NAME##\ }"; NAME="${NAME##release-}"; NAME="${NAME//-/.}"
-	[[ -n $NAME ]] && NAME="Version $NAME "
-
-	echo ${CMDNAME}
-	echo ${NAME}${VERSION}
-
-	echo -e "\nCopyright (C) 2010 Hacking Networked Solutions"
-	echo "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
+    echo "$(basename "${0}") - version 1.0.0"
+    echo -e "\nCopyright (C) 2010-2020 Hacking Networked Solutions"
+    echo "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
 	echo "This is free software: you are free to change and redistribute it."
 	echo "There is NO WARRANTY, to the extent permitted by law."
 }
 
 function helpscreen
 {
-	echo "Usage: ${CMDNAME} [OPTION]..."
+    CMDNAME=$(basename "${0}")
+    echo "Usage: ${CMDNAME} [OPTION]..."
 	echo "Reinstalls any packages which are installed but which do not have a"
 	echo "corresponding binary package available"
 	echo
@@ -36,12 +27,10 @@ function helpscreen
 
 # Init local vars
 CFGFILE=/etc/buildspace
-CMDNAME=$(basename ${0})
 DEPS="--with-bdeps n"
 
 # If the config file exists and we can read it do so
-[[ ! -r ${CFGFILE} ]] && echo "Error: No config file (or no read permissions) at ${CFGFILE}" >&2 && exit 2
-source ${CFGFILE}
+source ${CFGFILE} || echo "Error: No config file (or no read permissions) at ${CFGFILE}" >&2 && exit 2
 
 # Process command line switches
 while (( $# > 0 ))
@@ -69,7 +58,7 @@ do
 done
 
 # Check to make sure we are being run from inside the buildspace.
-[[ -z "${BUILDSPACE_NAME}" ]] && echo "ERROR: ${CMDNAME} should only be run inside a configured buildspace!" >&2 && exit 1
+[[ -z "${BUILDSPACE_NAME}" ]] && echo "ERROR: $(basename "${0}") should only be run inside a configured buildspace!" >&2 && exit 1
 
 # Remerge forgotten binaries!
 emerge -pvek world ${DEPS} 2>&1 1>&1 | \
@@ -78,4 +67,4 @@ emerge -pvek world ${DEPS} 2>&1 1>&1 | \
 
 [[ $? -eq 0 && -z ${PRETEND} ]] && emerge -pvek world ${DEPS} 2>&1 1>&1 | \
 	awk -F "] " '/\[ebuild.+\]/ { print $2 }' | \
-		awk '{print "=" $1}' | xargs | xargs -r emerge -1 --keep-going		
+		awk '{print "=" $1}' | xargs | xargs -r emerge -1 --keep-going
diff --git a/bin/update-buildspace b/bin/update-buildspace
--- a/bin/update-buildspace
+++ b/bin/update-buildspace
@@ -2,18 +2,8 @@
 
 function versioninfo
 {
-	VERSION="$Revision$"
-	VERSION="${VERSION%\ \$}"; VERSION="${VERSION#\:}"; VERSION="${VERSION##\ }"
-	VERSION="(CVS revision $VERSION)"
-	
-	NAME="$Name$"
-	NAME="${NAME%\ \$}"; NAME="${NAME#\:}"; NAME="${NAME##\ }"; NAME="${NAME##release-}"; NAME="${NAME//-/.}"
-	[[ -n $NAME ]] && NAME="Version $NAME "
-
-	echo ${CMDNAME}
-	echo ${NAME}${VERSION}
-
-	echo -e "\nCopyright (C) 2013-2018 Hacking Networked Solutions"
+    echo "$(basename "${0}") - version 1.0.0"
+    echo -e "\nCopyright (C) 2010-2020 Hacking Networked Solutions"
 	echo "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>."
 	echo "This is free software: you are free to change and redistribute it."
 	echo "There is NO WARRANTY, to the extent permitted by law."
@@ -21,7 +11,7 @@ function versioninfo
 
 function helpscreen
 {
-	echo "Usage: ${CMDNAME}"
+	echo "Usage: $(basename "${0}")"
 	echo "Automatically updates the build-space by downloading all required packages,"
 	echo "building updated packages, merging new configuration files, removing"
 	echo "redundant libraries and packages, rebuilding packages broken by the update"
@@ -43,8 +33,23 @@ function helpscreen
     echo "      --version                  output version information and exit"
 }
 
+function die
+{
+    local msg ev
+    msg="ERROR: ${1}"
+    ev="${2}"
+    
+    if [[ -z "${ev}" ]] || (( ev < 1 )); then
+        ev=1
+    fi
+    
+    echo "${msg}" >&2
+    exit "${ev}"
+}
+
 function okorfail
 {
+    # shellcheck disable=SC2181
 	if (( ! $? )); then
 		echo "ok." 
 	else
@@ -55,16 +60,18 @@ function okorfail
 
 # Update environment and source the profile
 env-update --no-ldconfig &>/dev/null
-source /etc/profile &>/dev/null
+# shellcheck disable=SC1091
+source /etc/profile &>/dev/null || die "Unable to source /etc/profile" 1
 
 # Init global vars
 OUTLOGLIB=/usr/lib/outlogger.sh
 CFGFILE=/etc/buildspace
-CMDNAME=$(basename ${0})
 EXITSTATUS=0
 
 # Workaround for python bug 13107 - http://bugs.python.org/issue13107
-[[ -z "$COLUMNS" ]] && export COLUMNS=80 || ( (( $COLUMNS < 80 )) && export COLUMNS=80 )
+if [[ -z "$COLUMNS" ]] || (( COLUMNS < 80 )); then
+    export COLUMNS=80
+fi
 
 # The default update command parameters.
 UPDATE_OPTS="--update --deep --newuse --with-bdeps=y @world"
@@ -106,31 +113,27 @@ done
 # Create the fetch options from the update options.
 FETCH_OPTS="--fetchonly ${UPDATE_OPTS}"
 
-
 # If the config file exists and we can read it do so, otherwise complain and quit
-[[ ! -r ${CFGFILE} ]] && echo "ERROR: Unable to read config file at ${CFGFILE}" >&2 && exit 1 
-source ${CFGFILE}
+# shellcheck disable=SC1090
+source ${CFGFILE} || die "Unable to read config file at ${CFGFILE}" 1
 
 # Include and initialise logging library
-[[ ! -r ${OUTLOGLIB} ]] && echo "ERROR: Unable to load outlogger library from ${OUTLOGLIB}" >&2 && exit 2
-[[ -z "${LOGPATH}" ]] && echo "ERROR: No LOGPATH set in ${CFGFILE}" >&2 && exit 2
-source ${OUTLOGLIB}
-init_logging ${LOGPATH}
+[[ -z "${LOGPATH}" ]] && die "No LOGPATH set in ${CFGFILE}" 2
+# shellcheck disable=SC1090
+source ${OUTLOGLIB} || die "Unable to load outlogger library from ${OUTLOGLIB}" 2
+init_logging "${LOGPATH}"
 
 # Check to make sure we are being run from inside the buildspace.
-[[ -z "${BUILDSPACE_NAME}" ]] && echo "ERROR: ${CMDNAME} should only be run inside a configured buildspace!" >&2 && exit 3
+[[ -z "${BUILDSPACE_NAME}" ]] && die "$(basename "${0}") should only be run inside a configured buildspace!" 3
 
 # Clean the portage and binary package temporary directories
 PTD=$(portageq envvar PORTAGE_TMPDIR)
-[[ -z "${PTD}" || (( ! $? )) ]] && echo "ERROR: Unable to locate PORTAGE_TMPDIR" >&2 && exit 4
-rm -rf ${PTD}/portage/*
-(( $? )) && echo "ERROR: Unable to clean ${PTD}/portage" >&2 && exit 5
-rm -rf ${PTD}/binpkgs/*
-(( $? )) && echo "ERROR: Unable to clean ${PTD}/binpkgs" >&2 && exit 5
+[[ -z "${PTD}" ]] && die "Unable to locate PORTAGE_TMPDIR" 4
+rm -rf "${PTD}"/portage/* || die "Unable to clean ${PTD}/portage" 5
+rm -rf "${PTD}"/binpkgs/* || die "Unable to clean ${PTD}/binpkgs" 5
 
 # If we are not being run from a TTY then set SENDMAIL and QUIET
-tty -s
-if (( $? )); then
+if ! tty -s; then
 	SENDEMAIL=1
 	QUIET=1
 fi  
@@ -151,7 +154,7 @@ exec_and_log pretend_update "emerge --color n --nospinner --pretend --verbose ${
 okorfail 6
 
 # If things are still working so far...
-if (( ! ${EXITSTATUS} )); then
+if (( ! EXITSTATUS )); then
 	# Ensure free space is available for distfiles
 	free-distfiles-space --free-delete --source "${LOGPATH}/pretend_update.out.log"
 
@@ -162,7 +165,7 @@ if (( ! ${EXITSTATUS} )); then
 fi
 
 # If things are still working so far...
-if (( ! ${EXITSTATUS} )); then
+if (( ! EXITSTATUS )); then
 	# Store and display current key package versions and slots.
 	PRE_PERL_PKG=$(qlist -I -C -v -e dev-lang/perl)
 	PRE_PYTHON_PKGS=$(qlist -I -C -v -e dev-lang/python | xargs)
@@ -194,6 +197,7 @@ if (( ! ${EXITSTATUS} )); then
 	echo
 												
 	# Ensure that key slotted packages are specified in world file and include slot number
+	# shellcheck disable=SC2086
 	if [[ -n $(manage-slot-in-world --add-installed --pretend ${KEEP_PACKAGES} ${KEEP_KERNELS}) ]]; then
 		echo "Ensuring that key packages are in world file and include slot number"
 		manage-slot-in-world --add-installed ${KEEP_PACKAGES} ${KEEP_KERNELS}
@@ -209,22 +213,24 @@ if (( ! ${EXITSTATUS} )); then
 fi
 
 # If things are still working so far...
-if (( ! ${EXITSTATUS} )); then
+if (( ! EXITSTATUS )); then
 	# Check to see if we have a deprecated profile.
 	if [[ -f "/etc/make.profile/deprecated" ]]; then
 		oldprofile=$(eselect --brief --colour=no profile show)
-		oldprofile=$(echo ${oldprofile})
+		# shellcheck disable=SC2116
+		oldprofile=$(echo "${oldprofile}")
 		newprofile=$(cat "/etc/make.profile/deprecated")
 		echo -n "Updating profile from ${oldprofile} to ${newprofile}..."
 		exec_and_log profile_update "eselect profile set ${newprofile}"
 		okorfail 7
 		env-update &>/dev/null
+        # shellcheck disable=SC1091
 		source /etc/profile &>/dev/null
 	fi
 fi
 
 # If things are still working so far...
-if (( ! ${EXITSTATUS} )); then
+if (( ! EXITSTATUS )); then
 	# Build updated packages
 	echo -n "Building updated packages..."
 	exec_and_log build_phase "emerge --color n --nospinner ${UPDATE_FLAGS} ${UPDATE_OPTS}"
@@ -247,11 +253,12 @@ if (( ! ${EXITSTATUS} )); then
 		exec_and_log gcc-config "gcc-config ${gcc_profile}${gcc_package}"
 		okorfail 10
 		env-update &>/dev/null
+		# shellcheck disable=SC1091
 		source /etc/profile &>/dev/null
 	fi
 
 	# If the kernel headers got an update and glibc didn't then rebuild it
-	if [[ ${PRE_HEADERS_PKG} != ${POST_HEADERS_PKG} && ${PRE_GLIBC_PKG} == ${POST_GLIBC_PKG} ]]; then
+	if [[ "${PRE_HEADERS_PKG}" != "${POST_HEADERS_PKG}" && "${PRE_GLIBC_PKG}" == "${POST_GLIBC_PKG}" ]]; then
 		echo -n "Rebuilding sys-libs/glibc against ${POST_HEADERS_PKG}..."
 		exec_and_log glibc_rebuild "emerge --color n --nospinner -1 sys-libs/glibc"
 		okorfail 11
@@ -291,9 +298,9 @@ if (( ! ${EXITSTATUS} )); then
 	POST_PERL_PKG=$(qlist -I -C -v -e dev-lang/perl)
 
 	# Create perl-cleaner arguement list
-	[[ ${POST_PERL_PKG} != ${PRE_PERL_PKG} ]] && \
+	[[ "${POST_PERL_PKG}" != "${PRE_PERL_PKG}" ]] && \
 		PERLCARGS="modules libperl ph-clean"
-	[[ ${POST_HEADERS_PKG} != ${PRE_HEADERS_PKG} ]] && \
+	[[ "${POST_HEADERS_PKG}" != "${PRE_HEADERS_PKG}" ]] && \
 		PERLCARGS="${PERLCARGS} phupdate"
 
 	# Ensure any perl packages broken by an update are rebuilt if needed
@@ -340,7 +347,7 @@ if (( ! ${EXITSTATUS} )); then
 	fi
 	
 	# If things are still working so far...
-	if (( ! ${EXITSTATUS} )); then
+	if (( ! EXITSTATUS )); then
 		# Ensure all required distfiles have been accessed
 		echo -n "Touching all required distfiles..."
 		exec_and_log touch_all "emerge -e --fetchonly world --with-bdeps y"
@@ -360,7 +367,7 @@ if (( ! ${EXITSTATUS} )); then
 
 	# Store any new news items for email attachment later
 	NEWSITEMS=$(eselect news count new)
-	if (( ${NEWSITEMS} > 0 )); then
+	if (( NEWSITEMS > 0 )); then
 		echo -n "Getting ${NEWSITEMS} news item(s) for later reading..."
 		exec_and_log news "eselect news read new"
 		okorfail 25
@@ -383,6 +390,7 @@ if (( ! ${EXITSTATUS} )); then
 	[[ -n "${POST_XDRV_PKG}" ]] && echo "    ${POST_XDRV_PKG}"
 				
 	# Display any slotted packages which are no longer available
+	# shellcheck disable=SC2086
 	if [[ -n $(manage-slot-in-world --remove-unavailable --pretend ${KEEP_PACKAGES} ${KEEP_KERNELS}) ]]; then
 		echo -e "\nThe following key packages are no longer available in portage"
 		manage-slot-in-world --remove-unavailable --pretend ${KEEP_PACKAGES} ${KEEP_KERNELS}
@@ -390,12 +398,12 @@ if (( ! ${EXITSTATUS} )); then
 fi
 
 # Display completion state
-if (( ! ${EXITSTATUS} )); then
+if (( ! EXITSTATUS )); then
 	echo -e "\nAutomated update of [${BUILDSPACE_NAME}] buildspace completed.\n"
-	date +%Y%m%d%H%M > $(portageq pkgdir)/timestamp.txt
+	date +%Y%m%d%H%M > "$(portageq pkgdir)/timestamp.txt"
 else
 	echo -e "\nAutomated update of [${BUILDSPACE_NAME}] buildspace failed.\n"
-	rm $(portageq pkgdir)/timestamp.txt
+	rm -f "$(portageq pkgdir)/timestamp.txt"
 fi
 
 # End logging redirect
@@ -405,12 +413,12 @@ end_log_redirect
 bzip_large_logs 102400
 
 # If we were asked to send email send the logs to the buildspace admin (or root).
-if [[ -n ${SENDEMAIL} ]]; then
+if [[ -n "${SENDEMAIL}" ]]; then
 	send_logs_by_email "Automated update of ${BUILDSPACE_NAME}" "${ADMIN_EMAIL:-root}"
 fi
 
 # If we aren't running in quiet mode show a list of the log files we generated during the update
-if [[ -z ${QUIET} ]]; then
+if [[ -z "${QUIET}" ]]; then
 	display_log_paths
 fi
 
